### ISSUE TITLE
Use purescript-node-http 0.3.1+

### ISSUE THREAD

**Issue by robkuz** [dancingrobot84/purescript-express#38]
Hi,

is there any chance to get a new version of purescript-express that uses version 0.3.1 of purescript-node-http? I tried it myself but I am stuck at this error.

    purescript-express/bower_components/purescript-node-fs/src/Node/FS/Sync.purs line 384, 
    column 36 - line 384, column 45

    Could not match type

    Eff
      ( buffer :: BUFFER
      | _0
      )
      Int

     with type

     Int

     while checking that type Eff
                           ( buffer :: BUFFER
                           | _0
                           )
                           Int
    is at least as general as type Int
    while checking that expression size buff
    has type Int
    in value declaration fdNext

    where _0 is an unknown type

    See https://github.com/purescript/purescript/wiki/Error-Code-TypesDoNotUnify for more information,
    or to contribute content related to this error.
    
    Compiling Node.FS.Sync
    * ERROR: Subcommand terminated with exit code 1

**Comment by dancingrobot84** [comment]
Hi, @robkuz 

1. From the trace you gave it looks like the error is in purescript-node-fs package. Please, find out the version of purescript and purescript-node-fs used in your build and report the problem [here](https://github.com/purescript-node/purescript-node-fs)

2. purescript-express uses express.js under the hood; it handles all network operations. I think there is a little possibility of interoperability with purescript-node-http, since the types used there are not necessarily  compatible with the structures used by express.js. However, I'll take a look at it sometime. If by that time you figure out how to do it, your PR will be certainly welcome.

**Comment by robkuz** [comment]
Hi @dancingrobot84 ,

I am not sure I understand: `bower.json` does include a dependency to `purescript-node-http` and possibly that somehow has a sub-dependency into `purescript-node-fs. Both of them are older versions and if both are updated to a more recent version it works (at least on my machine ;-) ).

I created a pull request.

Another issue: The compiler is warning about a lot about imports that do not adhere to Purescript's style. For example:

    [60/85 ImplicitImport] test/Test/Mock.purs:28:1

      28  import Control.Monad.Eff
            ^^^^^^^^^^^^^^^^^^^^^^^^

     Module Control.Monad.Eff has unspecified imports, consider using the explicit form:

       import Control.Monad.Eff (Eff)

If you like to I can clean that up. However if you don't like the proposed styling than I leave it as is.

**Comment by dancingrobot84** [comment]
Oh, sorry, my bad -- completely forgot that purescript-node-http was introduced for compatibility of `listenHttp(s)` methods after one of big changes. Yes, then I guess it should be updated.

Glad that you've solved the problem with node-fs. I'd certainly like if you clean up import warnings too, however, it could be a tedious work, so it's up to you whether to do it or not.

**Comment by robkuz** [comment]
@dancingrobot84 maybe I'll do some part tomorrow and some part next week ;-)
