### ISSUE TITLE
Update to Purescript 0.9.1

### ISSUE THREAD

**Issue by Risto-Stevcev** [dancingrobot84/purescript-express#44]
The dependencies and import statements need to be updated for Purescript 0.9.1

**Comment by kika** [comment]
I started working on this here https://github.com/kika/purescript-express
But I'm blocked by purescript-node-fs module which depends on purescript-datetime, which, in turn, is being redesigned https://github.com/purescript/purescript-datetime/issues/33 and will not be updated to 0.9.1 in its current form. As soon as they release datetime I'll continue on the 0.9.1 update.

**Comment by Risto-Stevcev** [comment]
Nice! Do you know if this repo is still maintained or if the maintainer is just mia?

**Comment by kika** [comment]
History of PRs shows that they are being merged, so the repo seems to be alive, just not actively developed. My `ToDoServer` implementation was accepted back in December.

**Comment by dancingrobot84** [comment]
@Risto-Stevcev @kika Yes, that's right. I'm not into purescript anymore, but can always review and accept occasional PR. If somebody wants to take ownership and develop the project more actively I'll be happy to transfer it.

**Comment by Risto-Stevcev** [comment]
@dancingrobot84 I'd be happy to take over the project unless @kika really wants to do it

**Comment by kika** [comment]
We're two steps closer, purescript-datetime was updated and I've just submitted PR for purescript-node-fs : https://github.com/purescript-node/purescript-node-fs/pull/30

I'll work on express using my local copy of node-fs meanwhile.

@dancingrobot84 I can take over the module, no problem. I use it for work and my product depends on it (not much currently, but I have plans to move more code from plain vanilla coffeescript+express to purescript). If you don't mind reviewing and accepting PRs I'm good with this too.

**Comment by dancingrobot84** [comment]
@Risto-Stevcev @kika Ok, then let's leave it how it is now until the time I can't review PRs anymore.

**Comment by kika** [comment]
We're almost there. Currently the only thing left is https://github.com/bodil/purescript-test-unit/pull/19
And people are working on it.

**Comment by kika** [comment]
All modules we were waiting for were updated and my fork compiles and runs. The only issue is tests. They were written using `purescript-test-unit` 3.0.0 which is *very* old and the API changed even before 0.9.1 release. I made some changes and resolved some minor problems, but work still needs to be done, as of now it is not able to pass Travis build because of the tests. Unfortunately, I can't devote much time now and finish the port of tests to the new 7.0.0 release of `purescript-test-unit`. 
But all the examples run and so far run successfully, so my fork could be picked up by anyone who needs functional `purescript-express` on 0.9.1
